version: 0.1

phases: 
  build:
    commands:
    - echo "this is build phase... zipping my lambda function"
    - zip -r deployment_package.zip index.js index.html
  post_build:
    commands:
    - echo " deploying to the lambda"
    - aws lambda update-function-code --function-name MyFunction4 --zip-file fileb://deployment_package.zip
artifacts:
  type: zip
  paths:
   - '*'
   
